#!/bin/bash
# Finish lab/PREREG-skin.md once all 15 runs are done: analysis, gzip raw, check the analysis reproduces from the gzipped
# files, commit and push cos/skin ONLY. If lab/RESULT-skin.md does not exist yet, writes an auto-generated one (verdict +
# full readout) so the result is never lost; a plain-language write-up can replace it.
cd "$(dirname "$0")/../.." || exit 1
D=lab/skin/raw
[ "$(git rev-parse --abbrev-ref HEAD)" = cos/skin ] || { echo "not on cos/skin"; exit 1; }
n=$(ls $D/*.done 2>/dev/null | wc -l); [ "$n" = 15 ] || { echo "only $n of 15 runs done"; exit 1; }
node lab/skin/analyse.js > lab/skin/analysis.txt || exit 1
for f in $D/*.err; do [ -s "$f" ] || rm -f "$f"; done
for f in $D/*.all.jsonl; do [ -f "$f" ] && gzip -9f "$f"; done
node lab/skin/analyse.js > /tmp/skin-recheck.txt && cmp -s /tmp/skin-recheck.txt lab/skin/analysis.txt || { echo "analysis does not reproduce from gz"; exit 1; }
if [ ! -f lab/RESULT-skin.md ]; then
  { echo "# RESULT - skin (AUTO-GENERATED by lab/skin/finish.sh; plain-language write-up pending)"; echo
    echo "Pre-registration: lab/PREREG-skin.md. Seeds 16-18, 450k ticks."; echo; echo "## Verdict"; grep '^=>' lab/skin/analysis.txt; echo
    echo '## Readout (node lab/skin/analyse.js)'; echo '```'; cat lab/skin/analysis.txt; echo '```'; } > lab/RESULT-skin.md; fi
git add lab/skin lab/RESULT-skin.md && git commit -qm "lab: SKIN results (seeds 16-18, 450k): $(grep '^=>' lab/skin/analysis.txt | sed 's/^=> //')" && git push -q origin cos/skin && git log -1 --format=%H && git ls-remote origin cos/skin
