#!/bin/bash
# Finish lab/PREREG-niche-v3.md once all 12 runs are done: analysis, gzip raw, check the analysis reproduces from the
# gzipped files, commit and push cos/niche-v3 ONLY. If lab/RESULT-niche-v3.md does not exist yet, writes an
# auto-generated one (verdict + full readout) so the result is never lost; a plain-language write-up can replace it.
cd "$(dirname "$0")/../.." || exit 1
D=lab/niche-v3/raw
[ "$(git rev-parse --abbrev-ref HEAD)" = cos/niche-v3 ] || { echo "not on cos/niche-v3"; exit 1; }
n=$(ls $D/*.done 2>/dev/null | wc -l); [ "$n" = 12 ] || { echo "only $n of 12 runs done"; exit 1; }
node lab/niche-v3/analyse.js > lab/niche-v3/analysis.txt || exit 1
for f in $D/*.err; do [ -s "$f" ] || rm -f "$f"; done
for f in $D/*.all.jsonl; do gzip -9f "$f"; done
node lab/niche-v3/analyse.js > /tmp/niche-v3-recheck.txt && cmp -s /tmp/niche-v3-recheck.txt lab/niche-v3/analysis.txt || { echo "analysis does not reproduce from gz"; exit 1; }
if [ ! -f lab/RESULT-niche-v3.md ]; then
  { echo "# RESULT - niche v3 (AUTO-GENERATED by lab/niche-v3/finish.sh; plain-language write-up pending)"; echo
    echo "Pre-registration: lab/PREREG-niche-v3.md. Seeds 13-15, 900k ticks."; echo; echo "## Verdict"; grep '^=>' lab/niche-v3/analysis.txt; echo
    echo '## Readout (node lab/niche-v3/analyse.js)'; echo '```'; cat lab/niche-v3/analysis.txt; echo '```'; } > lab/RESULT-niche-v3.md; fi
git add lab/niche-v3 lab/RESULT-niche-v3.md && git commit -qm "lab: NICHE v3 results (seeds 13-15, 900k): $(grep '^=>' lab/niche-v3/analysis.txt | sed 's/^=> //')" && git push -q origin cos/niche-v3 && git log -1 --format=%H && git ls-remote origin cos/niche-v3
